### ISSUE TITLE
コメント履歴見た目調整

### ISSUE THREAD

**Issue by hkj-hub** [hkj-hub/comment-atlatl#3]
追加されたことが分かりやすいようにアニメーションをつける

**Comment by hkj-hub** [comment]
> HTMLでcommentのクラス名が付いたdiv要素が画面に追加されたとき、左から入ってくるようなアニメーションをつけるCSSを教えてください

HTMLでcommentのクラス名が付いたdiv要素が画面に追加されたときに、左から入ってくるようなアニメーションをCSSで実装する方法を示します。

```css
.comment {
  opacity: 0; /* 初期状態では非表示にする */
  transform: translateX(-100%); /* 初期状態では左側に位置する */
  transition: opacity 0.5s ease-in-out, transform 0.5s ease-in-out; /* アニメーションのトランジションを設定 */
}

.comment.visible {
  opacity: 1; /* 要素が表示されるときに不透明度を1にする */
  transform: translateX(0); /* 要素が表示されるときに左から入ってくるように位置を変更 */
}
```

JavaScriptを使ってcommentクラス名の要素が画面に追加されたときに、visibleクラスを追加することでアニメーションを実行します。以下は、JavaScriptでのサンプルコードです。

```js
// commentクラス名の要素を取得
const commentElement = document.querySelector('.comment');

// Intersection Observerのコールバック関数
const intersectionCallback = (entries, observer) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      // commentクラス名の要素がビューポートに入った場合
      commentElement.classList.add('visible'); // visibleクラスを追加してアニメーションをトリガー
      observer.unobserve(entry.target); // オブザーバーの解除
    }
  });
};

// Intersection Observerのオプション
const options = {
  root: null, // ビューポートをルートとして使用
  rootMargin: '0px',
  threshold: 0 // 要素がビューポートに1%以上入ったときにコールバックを実行
};

// Intersection Observerの作成と開始
const observer = new IntersectionObserver(intersectionCallback, options);
observer.observe(commentElement);
```

上記のコードでは、Intersection Observerを使用してcommentクラス名の要素がビューポート内に入ったときにvisibleクラスを追加し、アニメーションをトリガーしています。これにより、要素が画面に追加されたときに左から入るアニメーションが実行されます。

**Comment by hkj-hub** [comment]
> cssのkeyframeを使って書いてください


CSSの@keyframesルールを使用して、commentのクラス名が付いたdiv要素が画面に追加されたときに、左から入ってくるアニメーションを実装する方法を示します。

```css
.comment {
  opacity: 0; /* 初期状態では非表示にする */
  transform: translateX(-100%); /* 初期状態では左側に位置する */
  animation: slideIn 0.5s ease-in-out; /* @keyframesで定義したアニメーションを適用 */
}

@keyframes slideIn {
  from {
    opacity: 0;
    transform: translateX(-100%);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}
```

上記のCSSコードでは、@keyframesルールを使用してslideInというアニメーションを定義しています。このアニメーションは、要素が初めて表示されるときに、左から徐々に現れるような効果を持ちます。fromとtoキーワードは、アニメーションの開始と終了を示しています。

また、animationプロパティを使ってslideInアニメーションを要素に適用しています。これにより、commentクラス名の要素が画面に追加されたときにアニメーションが実行されます。

JavaScriptを使わずに、純粋なCSSのみでアニメーションを実装しています。この方法を使用すると、アニメーションの定義がCSSの中で完結するため、シンプルでわかりやすいコードになります。

**Comment by hkj-hub** [comment]
> アニメーションが終わったあとはその状態のCSSにしておきたいです。

アニメーションが終わった後に、その状態のCSSを保持するためには、animation-fill-modeプロパティを使用します。これにより、アニメーションの最終フレームのスタイルを保持することができます。

以下のように、animation-fill-mode: forwards;を追加することで、アニメーションが終了した際にその最終フレームのスタイルが維持されます。

```css
.comment {
  opacity: 0; /* 初期状態では非表示にする */
  transform: translateX(-100%); /* 初期状態では左側に位置する */
  animation: slideIn 0.5s ease-in-out forwards; /* @keyframesで定義したアニメーションを適用し、最終フレームのスタイルを維持 */
}

@keyframes slideIn {
  from {
    opacity: 0;
    transform: translateX(-100%);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}
```

上記のCSSコードでは、animation-fill-mode: forwards;を.commentクラスに追加しました。これにより、アニメーションが終了したときに、要素は最終フレームのスタイルを保持します。つまり、アニメーション後の状態が維持されることになります。

このようにanimation-fill-modeプロパティを使うことで、アニメーションが終わった後もアニメーション後のスタイルを保持したままにすることができます。
